version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bharatai
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/bharatai
    depends_on:
      - db
      - redis
volumes:
  db_data:
